### ISSUE TITLE
App Crash on Launch

### ISSUE THREAD

**Issue by buitim** [imxieyi/waifu2x-ios#10]
Jailbroken iPhone 8 Plus on iOS 11.3.1 app crashes on launch

```Crash log shows:
Termination Description: DYLD, Symbol not found: _OBJC_CLASS_$_MPSNNFilterNode | R!eferenced from: /var/containers/Bundle/Application/0F3B5A32-D163-4B5E-954F-DF1BEE939DD0/waifu2x-ios.app/waifu2x-ios | Expected in: /System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders | in /var/containers/Bundle/Application/0F3B5A32-D163-4B5E-954F-DF1BEE939DD0/waifu2x-ios.app/waifu2x-ios
Triggered by Thread:  0
```

**Comment by imxieyi** [comment]
This issue is because MPSCNN symbols are incomplete on iOS 11. A fix has already been submitted to the App Store and is waiting for review. It is too bad that Apple won't allow developers to recall an update with severe issues.

**Comment by buitim** [comment]
Ahh yeah it really is. Thanks for the heads up though! And of course thank you for the quick response and fast reply. I'll downgrade in the meantime. Since you said you already submitted a fix, I'll go ahead and close.
