### ISSUE TITLE
Why is the image quality is a little worse than Waifu2x-caffe?

### ISSUE THREAD

**Issue by Cook21** [imxieyi/waifu2x-ios#11]
I tried upscaled this picture in the same parameters but the output is slightly different from the Waifu2x-caffe.
**waifu2x-ios config:**
![ios config](https://user-images.githubusercontent.com/55291103/64880701-68e2c100-d68b-11e9-8da1-05a9b05f31fa.png)

**waifu2x-caffe config:**
![pc config](https://user-images.githubusercontent.com/55291103/64880960-1a81f200-d68c-11e9-9ec6-5730b4afd68f.GIF)

**original image:**
![961884bfgy1fh5utux4zpj210q1fun9x](https://user-images.githubusercontent.com/55291103/64880936-05a55e80-d68c-11e9-9a9c-6b67867955a3.jpg)

**waifu2x-ios output(zoom in):**
![IMG_7734](https://user-images.githubusercontent.com/55291103/64881125-8cf2d200-d68c-11e9-8c87-5c6beae4862f.jpg)

**waifu2x-caffe output(zoom in):**
![IMG_7736](https://user-images.githubusercontent.com/55291103/64881140-94b27680-d68c-11e9-8f8e-7ba1fbc0b440.jpg)

The result of waifu2x-caffe looks cleaner especially around the edges of eyes and hairs.

**Comment by imxieyi** [comment]
Are you using Core ML backend on A12/A12X device? I tried your image on my 6s using MPSCNN and the result is the same as waifu2x-caffe.
[cid:2B3AA115-1C42-4D4E-A063-66CC360D67BE-L0-001]

在 2019年9月13日，19:18，Cook21 <notifications@github.com> 写道：

﻿

I tried upscaled this picture in the same parameters but the output is slightly different from the Waifu2x-caffe.
waifu2x-ios config:
[ios config]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F55291103%2F64880701-68e2c100-d68b-11e9-8da1-05a9b05f31fa.png&data=02%7C01%7C%7C3d56d91c4ecb4b3c959308d7386e563b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637039918846668902&sdata=9KNxP5V2CSjgk1Q8wSXCxkzNGcPeK6RQYJsLf5e%2Bdak%3D&reserved=0>

waifu2x-caffe config:
[pc config]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F55291103%2F64880960-1a81f200-d68c-11e9-9ec6-5730b4afd68f.GIF&data=02%7C01%7C%7C3d56d91c4ecb4b3c959308d7386e563b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637039918846678913&sdata=XQsjWaX7WavL7heyYkCqd5MF%2FPHtzAgYjYRMNijOJxs%3D&reserved=0>

original image:
[961884bfgy1fh5utux4zpj210q1fun9x]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F55291103%2F64880936-05a55e80-d68c-11e9-9a9c-6b67867955a3.jpg&data=02%7C01%7C%7C3d56d91c4ecb4b3c959308d7386e563b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637039918846688917&sdata=XuOhCS2nmvnjScHRRCNAZQGshUu9ED%2BOiqXsChcNDqI%3D&reserved=0>

waifu2x-ios output(zoom in):
[IMG_7734]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F55291103%2F64881125-8cf2d200-d68c-11e9-8c87-5c6beae4862f.jpg&data=02%7C01%7C%7C3d56d91c4ecb4b3c959308d7386e563b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637039918846698922&sdata=BsqtiReaTVRzj1hUxjXFWPHqMFAidxOOXDBKGCSmh2M%3D&reserved=0>

waifu2x-caffe output(zoom in):
[IMG_7736]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F55291103%2F64881140-94b27680-d68c-11e9-8f8e-7ba1fbc0b440.jpg&data=02%7C01%7C%7C3d56d91c4ecb4b3c959308d7386e563b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637039918846708933&sdata=9JJt9GzGA0DylkEQ1tP%2B0SGAmRu98aSkcZ8pAol%2BPWE%3D&reserved=0>

The result of waifu2x-caffe looks cleaner especially around the edges of eyes and hairs.

**Comment by Cook21** [comment]
Yes, I got this result on an A12 device but no, I was using MPSCNN backend. I just tried switching to CoreML and selecting the “CPU only” and the result became the same as waifu2x-caffe. Then I realised that there might also be some issue with A12's GPU, not as serious as Neural Engine though.
