### ISSUE TITLE
output result is noisy..

### ISSUE THREAD

**Issue by farazBhatti** [imxieyi/waifu2x-ios#13]
Hi, iver tried running your converted coreml models but i am not getting desired results. 
input image 
(100*100)
![Webp net-resizeimage](https://user-images.githubusercontent.com/37732181/68675793-6bbe3d00-057a-11ea-8790-51aefe733d40.png)

output image
(200*200)

![oie_jGgceZazR65k](https://user-images.githubusercontent.com/37732181/68675968-d40d1e80-057a-11ea-937b-3b44f2a7051e.png)

**Comment by imxieyi** [comment]
This looks like you are using wrong image channel format. Please refer to implementation in this repo.

**Comment by farazBhatti** [comment]
@imxieyi , yes ive made sure that image as input to model is of RGB format but still the output is the same.

**Comment by imxieyi** [comment]
Please refer to documentation on [Core ML](https://developer.apple.com/documentation/coreml/core_ml_api). Apparently image data you are feeding to the model is in wrong format. (This model needs RRRGGGBBB not RGBRGBRGB format)
