### ISSUE TITLE
13.4下CoreML性能又更高了？

### ISSUE THREAD

**Issue by SZCthebandit** [imxieyi/waifu2x-ios#15]
iPad Mini5 a12，pixiv下的jpg，low 降噪， 4x放大，原图比较小的话感觉ML比MPSCNN快一些，大图感觉没啥区别。是苹果鸡血驱动还是我理解错了文档里的意思（不应该是MPSCNN在新设备上更快么）

**Comment by imxieyi** [comment]
MPSCNN的目的并不是提高性能，而是为了保证稳定的输出质量。Core ML在A12及以上芯片会因为系统优化产生精度下降的问题(#8)，iOS13有很大改进但并没有彻底解决问题。
