### ISSUE TITLE
[Feature Request]CLI输入和输出支持文件夹

### ISSUE THREAD

**Issue by i0ntempest** [imxieyi/waifu2x-ios#19]
可否支持放大给定文件夹下的所有图片，并批量指定输出文件夹和图片扩展名？

**Comment by imxieyi** [comment]
可能会考虑加入这个功能。通过脚本实现应该不难，可以暂时先用脚本应付一下。

**Comment by i0ntempest** [comment]
目前用了一个loop应付掉了。在caffe那边因为它每次运行都有一个cuDNN initialize，输入输出文件夹比iterate over files要快很多，如果这边没有这种问题的话那其实问题不大。

**Comment by imxieyi** [comment]
本app使用的是Metal，并不需要做任何初始化。读取模型确实需要消耗时间，但是和实际处理时间相比可以忽略不计。

**Comment by imxieyi** [comment]
最新的版本（6.2）添加了`--input-dir`、`--output-dir`、`--recursive`、`--output-format`选项用于处理文件夹，在Real-CUGAN模型上使用应该可以因为不需要重复加载模型大大加快批量处理速度。

**Comment by i0ntempest** [comment]
用了十张2000*1125的图片测试，放大两倍，节省时间6.2秒。感谢！
另外如果在输入输出文件夹的时候能有一个启用像用GUI处理后的自动重命名（比如_cugan_conservative_2x_i1.00）的开关就更好了
