### ISSUE TITLE
[enhancement idea] MacOS version

### ISSUE THREAD

**Issue by amnesic** [imxieyi/waifu2x-ios#2]
Any plan to port this smart project to MacOS ? High Sierra version has CoreML framework I think now.

**Comment by imxieyi** [comment]
Currently there is no plan to port it to macOS.
NSImage in AppKit(macOS) and UIImage in UIKit(iOS) is not the same. So it requires a lot of work to port it to macOS.
However, there are already many other implementations of waifu2x which are compatible with macOS. I suggest you to use one of them instead.
