### ISSUE TITLE
[Enhancement/macOS]重启保留文件权限，或给予特定文件夹RW权限

### ISSUE THREAD

**Issue by i0ntempest** [imxieyi/waifu2x-ios#20]
每次系统重启都需要打开app重新给权限，CLI才能正常工作。有没有办法保存文件权限？
或者，是否可以用entitlements永久允许读写某些文件夹？以我的use case来说的话一直允许~/Pictures就够了，大部分人的话再加上~/Downloads也应该够了。这俩都有对应的ent应该可以直接从Xcode里启用。
https://developer.apple.com/documentation/security/app_sandbox

Thanks

**Comment by imxieyi** [comment]
找到原因了，保存bookmark的时候没有带上权限，下个版本就会修复。

https://stackoverflow.com/questions/62470433/swift-url-bookmark-permissions-lost-after-computer-restart

**Comment by i0ntempest** [comment]
另外能把图标稍微整好看点吗，现有图标套一个big sur的图标边框就可以，四角方方的着实有点难看

**Comment by i0ntempest** [comment]
感谢修复
