### ISSUE TITLE
Catalyst version: Image settings window unresponsive after upscale.

### ISSUE THREAD

**Issue by ArguingMeadows** [imxieyi/waifu2x-ios#21]
Hi there, 

In the latest update for the the MacOS Catalyst version, if you upscale a photo, and then go back and upscale a new one, the image setttings (MPSCNN/cunet, Noise Level, etc.) window becomes unresponsive. The only way to get around it is to close the program entirely and start it back up.

**Comment by imxieyi** [comment]
Are you using Big Sur or Catalina? This issue didn't happen with Catalina before the update. Looks like it wasn't fully fixed in the recent update.

**Comment by ArguingMeadows** [comment]
M1 with Big Sur.

**Comment by imxieyi** [comment]
SwiftUI hit test in Mac Catalyst seems to be broken on Big Sur. Even iOS version on M1 Mac is broken in the same way. A potential fix is to convert iOS views to macOS native views, which can be done by changing [UI Idiom](https://developer.apple.com/documentation/uikit/mac_catalyst/choosing_a_user_interface_idiom_for_your_mac_app). However, this requires dropping support for Catalina. Also, a lot of optimizations are needed to make it feel right on macOS. For now, please consider using CLI version before this is completely fixed (likely recently). Sorry for the inconvenience!

**Comment by ArguingMeadows** [comment]
It's a minor inconvenience, I just wanted to bring it to your attention. I personally like this version better so I'll be sticking with it for the time being. Thanks again, and I look forward to more updates.

**Comment by imxieyi** [comment]
It turns out that changing UI Idiom still won't fix this issue. I moved the setup interface to a separate window instead. Please update to the latest version in Mac App Store and it should be fixed.
