### ISSUE TITLE
能否加一个不重新加载新图片

### ISSUE THREAD

**Issue by HanHan233** [imxieyi/waifu2x-ios#22]
我用的是iPad（第6代），在处理一张图片时，每次都是在重新加载图片的那一步闪退，能否加个不重新加载新图片？

**Comment by imxieyi** [comment]
处理开始时是否有看到内存不足的警告？

**Comment by imxieyi** [comment]
你可以试试用最新版将PNG编码器换到libpng，应该能缓解这个问题。
