### ISSUE TITLE
为什么MacBook M1 不能在core ML中使用神经网络引擎

### ISSUE THREAD

**Issue by wisermonk** [imxieyi/waifu2x-ios#24]

**Comment by imxieyi** [comment]
Apple并没有提供Neural Engine的API。目前唯一可能使用的办法就是通过设置Core ML的[computeUnits](https://developer.apple.com/documentation/coreml/mlmodelconfiguration/3022235-computeunits)。具体是否真的使用是Core ML框架做决定。经过测试waifu2x的模型即使选择`.all`也还是在GPU上运行。可能M1上的Neural Engine暂时并没有对第三方app开放。

**Comment by gnattu** [comment]
在以前的历史版本中 选择ANE后通过`powermetrics`可以看到ANE有不低的能耗，但是GPU没有，我认为这说明ANE至少在某个历史版本中是可以正常使用的

**Comment by imxieyi** [comment]
测试了一下确实现在ANE能用了，可能是以前的macOS版本不行。下次更新会重新启用macOS的ANE选项。

**Comment by imxieyi** [comment]
https://github.com/imxieyi/waifu2x-ios/wiki/Info-about-different-ML-backend#quality-comparison

做了些进一步的测试发现M1上的ANE相对MPSCNN画质下降小到可以忽略，和iPhone上面相比要好很多。不过考虑到Core ML因为系统更新出问题在过去发生过很多次，如果对速度不敏感还是建议使用MPSCNN。

**Comment by imxieyi** [comment]
Mac Catalyst版已经更新，iOS版会在下个版本跟进。
