### ISSUE TITLE
Big Sur风格的icon

### ISSUE THREAD

**Issue by i0ntempest** [imxieyi/waifu2x-ios#25]
我用figma摸了一个（但是原图标我只有256分辨率的），不嫌弃可以直接拿去用
![Icon-512](https://user-images.githubusercontent.com/16017904/114274999-74f35800-9a53-11eb-89a3-34ac87b1e971.png)
用这个链接可以克隆走编辑：https://www.figma.com/file/Hx17krj3rSbYQLdZg7plOe/waifu2x-Big-Sur

**Comment by imxieyi** [comment]
谢谢！不过macOS不支持在app内更换图标，你可以考虑转成icns后手动更换。

**Comment by i0ntempest** [comment]
我已经用上了，我意思你可以拿走直接替换现有的图标

**Comment by imxieyi** [comment]
根据以往的经验每次修改UI或者图标都会有些人因此给差评，所以默认图标还是别改了。

**Comment by i0ntempest** [comment]
那那些人可真是心把，不过好吧
