### ISSUE TITLE
it seems to be different code from the app released in the App Store

### ISSUE THREAD

**Issue by shutosg** [imxieyi/waifu2x-ios#26]
Hi, developer.

Thank you for releasing a great app and making the source code open!
But, it seems to be different code from the app released in the App Store.
I would like to learn by reading the source code of the released version.
Could you please update the repository?

Thanks.

**Comment by imxieyi** [comment]
I had been keeping two versions in sync back in 2017. However, after someone took my code for [waifu2x-mac](https://github.com/imxieyi/waifu2x-mac) and published it as a paid app on the App Store even without designing their own UI, I decided to stop updating this open source version. As an individual open source developer this is the most offensive thing to experience.


I'm not going to update this version as long as it is still working in the foreseeable future. However, I can tell you the major improvements in the App Store version. Specifically:
- Use [vImage](https://developer.apple.com/documentation/accelerate/vimage) to convert data format for Core ML. This significantly reduces CPU usage.
- Also use vImage to process alpha channel.
- Batch input via [this API](https://developer.apple.com/documentation/coreml/mlmodel/3088750-predictions). This significantly speeds up process on ANE.

**Comment by shutosg** [comment]
OMG... That's very unfortunate.
Okey, I understand and thank you for the info.
BTW, do you use any framework for fancy UI and animations?

**Comment by imxieyi** [comment]
The new UI is mostly built on [SwiftUI](https://developer.apple.com/xcode/swiftui/.

**Comment by shutosg** [comment]
SwiftUI!
I see, thank you very much.
