### ISSUE TITLE
Hope the future version could support batch-import and export

### ISSUE THREAD

**Issue by Ry0uk** [imxieyi/waifu2x-ios#3]
In the current version, it could only choose one picture one time and you must choose an action after the process , then you could do the next, and it’s a waste of time, hope the next version could choose more pictures one time (even up to ten or more pictures ) , and t can save time :)

**Comment by imxieyi** [comment]
Actually this app is not intended for heavy use, e.g. bulk processing. It's much better to use other implementations on PC when you want to do that.

However, I will still consider add this feature in a future release.

**Comment by kgriesbach** [comment]
I [forked the mac port](https://github.com/kgriesbach/waifu2x-mac) and added some bulk processing. It's really slow and (not optimized at) all, but it mostly works :-)

**Comment by imxieyi** [comment]
I have implemented this function in the latest version on App Store. Feel free to update it.

**Comment by weysss** [comment]
這個到底怎麼看那種圖片呀

**Comment by imxieyi** [comment]
> 這個到底怎麼看那種圖片呀

你怕是对这个项目有什么误解。。。
