### ISSUE TITLE
[Feature Request]添加 CUNet 模型

### ISSUE THREAD

**Issue by magic-akari** [imxieyi/waifu2x-ios#30]
或者能否给予更多的指导。我仅有一些通用的编码知识，没有机器学习相关的经验。
我在尝试转换 waifu2x 里的 CUNet 预训练模型到 Core ML 模型，但是非常苦手。

我已经在环境里安装好了 conda 和 coremltools，然而样例代码里做的事情与我期望的有很大差别。

**Comment by imxieyi** [comment]
CUnet模型无法转换到Core ML，只能用MPSCNN手动搭建。如果想学习的话建议不要尝试CUnet模型，因为手动搭建基本就是机械重复的动作，没有太大学习价值。

**Comment by magic-akari** [comment]
了解了，感谢回复。
