### ISSUE TITLE
[Feature request] Option to save to source folder by default

### ISSUE THREAD

**Issue by morning-paradigm** [imxieyi/waifu2x-ios#32]
The way the app works now, you have to choose an output folder for every conversion.
Most of the time I'd prefer to save to the source folder alongside the original files.

Also it's unclear what happens if you click "Don't show again".
![image](https://user-images.githubusercontent.com/39773982/127865984-364c37e1-c617-41fc-98db-89df3d48af33.png)

**Comment by imxieyi** [comment]
As the name suggests it will skip this dialog in the future. It wasn't shown as red text before Big Sur though.

**Comment by morning-paradigm** [comment]
Does that mean it will save to the last selected directory? Or to ~/Documents?
Either way it's not a desirable behaviour for me personally.

**Comment by imxieyi** [comment]
No. It will still prompt you to choose save destination. Saving the last selected directory is a good suggestion. Keep in mind that due to sandbox restrictions even if it's implemented it may not always work as you expect.

**Comment by imxieyi** [comment]
This feature is now available in the latest version of the new "waifu2x" Mac app.
