### ISSUE TITLE
能不能加一个像ios照片那种双指滑动进行多选的功能？

### ISSUE THREAD

**Issue by code4cc** [imxieyi/waifu2x-ios#33]
能不能加一个像ios照片那种双指滑动进行多选的功能？

**Comment by code4cc** [comment]
多张图片进行处理时会自动返回顶部，又没有处理进度，能不能再加一个处理进度条？

**Comment by imxieyi** [comment]
可以考虑在ios照片里面选完图片后通过“共享”菜单启动app，图片会被自动导入。app最上方会显示图片总数，处理时应该会自动滚动到当前图片，可以通过左上角数字判断当前进度。

**Comment by code4cc** [comment]
> 可以考虑在ios照片里面选完图片后通过“共享”菜单启动app，图片会被自动导入。app最上方会显示图片总数，处理时应该会自动滚动到当前图片，可以通过左上角数字判断当前进度。

但是这样子弄waifu2x的删除原图功能用不了了，保存图片后没弹出删除原图的提示

**Comment by imxieyi** [comment]
新的image picker已经支持此功能，请将app更新到最新版。
