### ISSUE TITLE
add support for Real-ESRGAN

### ISSUE THREAD

**Issue by sayomelu** [imxieyi/waifu2x-ios#34]
https://github.com/xinntao/Real-ESRGAN

as the comparison provided by [Anime4K](https://github.com/bloc97/Anime4K)

![Comparison](https://github.com/bloc97/Anime4K/raw/master/results/Comparisons/Cropped_Screenshots/Higurashi_360p_4K.png)

**Comment by sayomelu** [comment]
more comparison https://github.com/xinntao/Real-ESRGAN/blob/master/docs/anime_model.md

**Comment by imxieyi** [comment]
I already took a look at this a few weeks ago and have plan to port it to iOS.The only issue is that the model is very big, which means the performance on mobile devices may not be very practical.

**Comment by imxieyi** [comment]
The Real-ESRGAN models are now available on the iOS App Store verision. Feel free to update.
