### ISSUE TITLE
iOS最新版本购买后切换AppStore账号会丢失购买

### ISSUE THREAD

**Issue by Cairetina** [imxieyi/waifu2x-ios#36]
比如在国区购买安装后切换到另一个区的账号或退出登陆，额外模型就会无法使用

**Comment by imxieyi** [comment]
还真是。这个问题App Store测试环境完全测不出来。。。

应该是因为[StoreKit 2](https://developer.apple.com/storekit/)目前只能获取当前登录账号的内购项目。

已经跟Apple反馈这个问题。目前已经切换回老的StoreKit 1。请等待至少12个小时后应该可以恢复正常，可能需要科学上网从Firebase获取远程配置。

**Comment by imxieyi** [comment]
切到StoreKit 1后遇到了大量的崩溃问题。。。暂时还是切回StoreKit 2了。。。

**Comment by Cairetina** [comment]
> 切到StoreKit 1后遇到了大量的崩溃问题。。。暂时还是切回StoreKit 2了。。。

之后会有迁移回 StoreKit 1 的计划吗

**Comment by imxieyi** [comment]
已经提交包含手动切换到StoreKit 1开关的新版，由于节假日审核慢可能会稍晚才能上线。

**Comment by Cairetina** [comment]
> 已经提交包含手动切换到StoreKit 1开关的新版，由于节假日审核慢可能会稍晚才能上线。

好的，非常感谢

**Comment by imxieyi** [comment]
审核比预想中快很多，带StoreKit 1开关的新版（5.1.1）已经上线了，请到App Store升级后应该可以解决购买丢失的问题。

**Comment by Cairetina** [comment]
> 审核比预想中快很多，带StoreKit 1开关的新版（5.1.1）已经上线了，请到App Store升级后应该可以解决购买丢失的问题。

切换账号后可以正常使用了，再次感谢
