### ISSUE TITLE
macOS 无法购买模型

### ISSUE THREAD

**Issue by gnattu** [imxieyi/waifu2x-ios#37]
点击Purchase提示`Failed to retrieve product information.`

Restore Purchase 提示`This account has not purchased this item.`

相同Apple ID在iOS上已经购买过模型，似乎是iOS App切换到macOS App的时候IAP产生的问题？

**Comment by imxieyi** [comment]
mac上面是单独的内购项目（因为之前就是独立的app）。不知为何app和内购项目的审核是分开的，目前内购项目还在等待审核（此处又要吐槽Apple审核100遍）。由于最近节假日可能需要花更长时间。

**Comment by imxieyi** [comment]
内购项目审核刚刚通过了，应该很快就能购买。如果你已经买了旧版（waifu magnifier）可以更新旧版app登记信息获取免费升级。
