### ISSUE TITLE
5.2.1出现切换账号丢失购买问题

### ISSUE THREAD

**Issue by simonkimi** [imxieyi/waifu2x-ios#38]
在国区购买后，如果切换到其他账号就会丢失购买信息。

但是如果切换回国区后，勾选允许切换apple id再点恢复购买，仍然会提示是用另一个id购买的，必须关掉切换账号才能恢复购买，但是这样就不能切换账号了。。。

![E58F4344-DE43-4A56-9DAB-B107D00E9C9C](https://user-images.githubusercontent.com/49084387/148836450-d9e0af1d-53d0-4698-a940-d023da9615f0.png)

**Comment by imxieyi** [comment]
有尝试用国区账号重新下载app吗？我记得如果app和内购项目不在同一个账号购买会出问题。关于这个问题的原因如果你感兴趣的话可以查看#36。

**Comment by simonkimi** [comment]
重新下载后就会是这种情况: 国区下载下来默认就是已购买状态, 切换账号后又变成未购买状态, 再切换回国区再次变成已购买状态, 没有切换选项了

**Comment by imxieyi** [comment]
这确实是个问题。是否可以把你的安装ID（在app内设置里面可以找到）发到support@waifu2x.app？等至少12个小时后再打开app同步firebase设置后应该能解决。（可能需要科学上网才能访问firebase服务器）
