### ISSUE TITLE
【Question】Is there a separate charge for model unlocking for the mac app version and the ios/ipados app version?

### ISSUE THREAD

**Issue by mofneko** [imxieyi/waifu2x-ios#39]
If you check the in-app purchase section of the app store, you will see that there is a menu item called "mac version" in addition to the regular model unlock.
Do I need to pay extra to use the unlocked IOS version in the mac app?

Quote: https://apps.apple.com/us/app/waifu2x/id1286485858

```
In-App Purchases
Additional Models
$6.99
Additional Models for Mac
$6.99
Three tips
$2.99
Tip
$0.99
Two tips
$1.99
```

**Comment by imxieyi** [comment]
Yes. Two versions need to be purchased separately.

**Comment by mofneko** [comment]
thank you for your reply.
Actually, I would like to purchase both to support the development, but unfortunately I can not purchase the mac version yet because I am in the environment of macos11.
I will use the ios version for a while.
If possible, I would be grateful if you could make the mac version compatible with macos11.

**Comment by imxieyi** [comment]
This app makes use of a lot of features only available on iOS 15 and macOS 12. So unfortunately it will require too much effort making it compatible with older versions.

You can consider mounting your macOS drive to iOS device via samba. Using `specified path` mode you can write output images directly to your Mac.
