### ISSUE TITLE
[Feature Request]希望添加Real-CUGAN

### ISSUE THREAD

**Issue by cyy911** [imxieyi/waifu2x-ios#42]
项目地址：[https://github.com/bilibili/ailab/tree/main/Real-CUGAN](url)
对比：[https://github.com/bilibili/ailab/tree/main/Real-CUGAN#1-%E6%95%88%E6%9E%9C%E5%AF%B9%E6%AF%94](url)
感谢

**Comment by imxieyi** [comment]
已经注意到这个项目了，看了一眼readme感觉`百万级高清二次元patch dataset`也太像某宝风格了（`GTX 760电竞级显卡` `24核双路xeon秒i9`）（说得好像他们的训练集就公开了一样）。感觉得再观望一段时间。以目前他给的样例效果其实锐化程度远不如real-esrgan，我怀疑绝大多数用户还是倾向于更加锐化的效果。

**Comment by imxieyi** [comment]
最新的App Store版本（6.0）已经添加该模型，不过由于iOS设备内存太小必须将图片分割成非常小的块，导致性能不太理想（虽然还是比Real-ESRGAN快）。
