### ISSUE TITLE
Prevent Sleep during long tasks

### ISSUE THREAD

**Issue by mattbisme** [imxieyi/waifu2x-ios#44]
I noticed when processing large files, such as videos, the app will not prevent the system from sleeping. While upscaling a job overnight, the computer fell asleep. Upon waking it, the app continued the upscale job. 

Instead, it would be best if the app prevented system sleep while running a task.

**Comment by imxieyi** [comment]
This feature was already implemented in iOS. The same API doesn't work in macOS though.

Looks like it's not easy preventing system sleep on macOS. It requires calling some low-level OS API, which is not easy to do in a Mac Catalyst app and may not be approved by App Store reviewers.

You can try to enable `Prevent computer from sleeping automatically when the display is off` in macOS Settings and connect your Mac to power while processing.

This feature may come in a future update if there is a viable way to do it. But don't get your hopes too high.

**Comment by imxieyi** [comment]
It is possible to prevent sleep. However, it also prevents the display from turning off automatically. Therefore the display will be kept on through the whole process. Will this work for you?

**Comment by mattbisme** [comment]
Yes, it's normal for apps that prevent sleep to keep the display on as well. That's no problem. It's possible to use a hot corner to turn off the screen without putting the computer to sleep (I do this with Handbrake all the time). Having the computer stay awake during a job is much better than having the job never finish! Thanks!

**Comment by imxieyi** [comment]
This feature is now supported in the latest version (6.0). Feel free to update.
