### ISSUE TITLE
图片选择器选中后无法回到主界面

### ISSUE THREAD

**Issue by Cairetina** [imxieyi/waifu2x-ios#46]
在 App 主界面点 + 号从相册选择图片时，选中图片点击添加后图片选择器不会消失，点击取消也没有反应，而且选中的内容必须手动反选后才能保住不被重复添加

**Comment by imxieyi** [comment]
是100%会发生吗？试试从顶部往下划呢？

**Comment by Cairetina** [comment]
是的，必定发生，iOS 和 macOS 端都试了，顶部下划也没有反应

**Comment by imxieyi** [comment]
那就奇怪了，你是打开app后直接就点+号了吗？

**Comment by Cairetina** [comment]
是的

**Comment by Cairetina** [comment]
我的系统版本是 iOS 15.4 RC 和 macOS 12.3 RC，两边表现不一样的话可能是因为这个？

**Comment by imxieyi** [comment]
找到原因了，因为出于不明原因app的默认配置出问题而使用的是系统内置的picker，和SwiftUI有兼容性问题，最近更新大改了UI相关的底层逻辑后忘记测试了。

如果有条件是否可以尝试打开科学上网后再打开app？如果你没有屏蔽Firebase服务器的话应该会在10秒钟左右下载正确的配置。

**Comment by Cairetina** [comment]
正常了，感谢

**Comment by imxieyi** [comment]
新的6.0.1版本已经彻底解决这个问题，也解决了Real-CUGAN在iOS 15.4不可用的问题，如有需要请前往App Store更新。
