### ISSUE TITLE
macos CLI how to deal with images 

### ISSUE THREAD

**Issue by nevertoday** [imxieyi/waifu2x-ios#47]
请问，有没有关于该软件如何处理macos 下图片的命令相关教程？

纯新手，也已购买对应解锁部分功能。 

谢谢

**Comment by imxieyi** [comment]
不建议在没有命令行使用经验的情况下用命令行版本。如果你不和其他程序或脚本搭配使用就没有必要用命令行。

大部分情况下你可以通过设置alias方便调用app：
```bash
alias waifu2x=/Applications/waifu2x.app/Contents/MacOS/waifu2x
```
也可以将alias加入`.bashrc`或者`.zshrc`。

然后使用`waifu2x --help`查看app支持的命令行参数。

由于沙盒的要求，如果需要输入输出文件请先打开app的主界面，将文件所在的目录拖进app授权访问，然后在命令行使用绝对路径如`$(pwd)/input.jpg` 。

**Comment by nevertoday** [comment]
谢谢， 我今天下午已经处理好了
ln -s 之类的，hin 快就搞好了。&nbsp;&nbsp;

沙盒这点我也看了你之前的文档， 确实这一步有点点“不愉快”。


waifu2x.mac 的强大毋容置疑， 我的需求中确实很多环境下都是需要配合其他命令使用的。


这种优化质量的感觉真的hin好，希望世界早日进化到， 更更更智能的一天（模糊）【人类视角】话的更清晰。






----


谢谢您开发出这么优秀的插件~&nbsp;




ps 我个人拙见， 操作界面的用户体验上，n个细节感觉有点点不是很愉快， 我平替对比：permute&nbsp;










------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi ***@***.***&gt;; 
发送时间: 2022年3月18日(星期五) 晚上6:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imxieyi/waifu2x-ios] macos CLI how to deal with images  (Issue #47)





 
不建议在没有命令行使用经验的情况下用命令行版本。如果你不和其他程序或脚本搭配使用就没有必要用命令行。
 
大部分情况下你可以通过设置alias方便调用app：
 alias waifu2x=/Applications/waifu2x.app/Contents/MacOS/waifu2x
 
也可以将alias加入.bashrc或者.zshrc。
 
然后使用waifu2x --help查看app支持的命令行参数。
 
由于沙盒的要求，如果需要输入输出文件请先打开app的主界面，将文件所在的目录拖进app授权访问，然后在命令行使用绝对路径如$(pwd)/input.jpg 。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nevertoday** [comment]
请问，大神，waifu2x 还可以进一步进化吗？ 比如修复旧照片中的人脸， 并修复整个照片的背景吗？
我之前，用过这个https://github.com/TencentARC/GFPGAN
效果很好，但缺点就是只能优化人脸。

**Comment by imxieyi** [comment]
这模型太大了，348M肯定告别移动设备了，就算加了也大概率只能支持Mac。

**Comment by nevertoday** [comment]
请教大神一个问题：
能让这个CLI工具，同时支持多个图片同时被处理运行吗？

当前我使用这个工具的事后， 总是提醒我只能运行一张图片


Or 是我版本太低 目前命令模式， 已经有办法支持多个图片了？

谢谢。



Sent with a Spark
在 2022年3月18日 +0800 PM9:49，chenxiang ***@***.***>，写道：

**Comment by imxieyi** [comment]
如果你指的是处理文件夹的话，请使用`--input-dir`和`--output-dir`参数指定文件夹。

如果你指的是同时处理多张图的话，请使用脚本同时运行多个waifu2x，比如Python可以用[multiprocessing](https://docs.python.org/3/library/multiprocessing.html)，但处理速度可能会因为多个进程抢ANE或者GPU资源而更慢。

**Comment by nevertoday** [comment]
感觉电脑只能扛住一张图一次， 我还是保守方案比较好。
