### ISSUE TITLE
"Performance" section appears empty when using "Basic" mode

### ISSUE THREAD

**Issue by mattbisme** [imxieyi/waifu2x-ios#49]
![image](https://user-images.githubusercontent.com/5126680/162095946-0116f632-6171-49de-a66c-fcd2fa43c623.png)

This appears to only be a visual bug, from what I can tell. The heading for "Performance" options appears even when there are no settings to change. This actually confused me at first; I thought maybe the app was broken and I was unable to see anything below "Performance."

Since the "Batch size" setting appears under "Performance" when in Advanced mode, I'm guessing that this is only a visual bug; that it's actually supposed to be hidden when in Basic mode.

**Comment by imxieyi** [comment]
Yes it's only a harmless visual bug. It's still worth fixing though.

**Comment by imxieyi** [comment]
Fixed in 6.2.1
