### ISSUE TITLE
Image Chooser of Batch Mode Cannot Show Latest Images

### ISSUE THREAD

**Issue by 0u0u0** [imxieyi/waifu2x-ios#5]
I send some images by AirDrop, however, they cannot be seen in the image chooser of batch mode. Yet they can be found in Photo app and other mode's image chooser. 
Also, some album preview of the image chooser show wrong images. 

iPhone 8 Plus (Global)
iOS 12
waifu2x 3.0 (build 2219)

**Comment by 0u0u0** [comment]
I tried on my iPad, and amazingly it worked fine. 

iPad 5 (Wi-Fi)
iOS 11.4.1
waifu2x 3.0 (build 2219)

**Comment by imxieyi** [comment]
If you use AirDrop to transfer images, the creation time of the images remains unchanged. `Albums tab` in Photos app sort images by time added. `Photos tab` in Photos app sort images by creation time. In this app, non-batch mode use exactly the same image chooser as `Albums tab` in Photos app. However it does not support multiple selection. So a customized image picker which sort images by creation time is used in this mode. In the next release it will be changed to sort by time added to match with non-batch mode.

**Comment by 0u0u0** [comment]
Thanks for your reply and development of the application!

**Comment by 0u0u0** [comment]
新的图片选择器似乎还是创建日期排序？

**Comment by imxieyi** [comment]
从iOS 13.0开始，之前使用的让照片排序和系统一致的方法已经失效。请尝试从照片app中选择图片并点击分享菜单里面的“使用waifu2x放大”。

Since iOS 13.0, the workaround to make images sorted exactly as photos app is no longer working. Please try selecting images from photos app and invoke “scale using waifu2x” from share menu instead.

**Comment by 0u0u0** [comment]
好的，感谢回复
