### ISSUE TITLE
CLI Video Processing crashes when using real-cugan model on MacOS

### ISSUE THREAD

**Issue by mmkzer0** [imxieyi/waifu2x-ios#52]
I have setup waifu2x for CLI usage on my M1 MacBook Pro. When I try to process a mp4 video with the command

> alias waifu2x=/Applications/waifu2x.app/Contents/MacOS/waifu2x
ffmpeg -i input.mp4 -pix_fmt rgba -f rawvideo -loglevel quiet - |
  waifu2x -m real_cugan --cugan-scale 2 --cugan-variant conservative --raw --width 1920 --height 1080 |
  ffmpeg -f rawvideo -pix_fmt rgba -s:v 3840x2160 -r 23.98 -i - -c:v h264_videotoolbox output.mp4

using real-cugan as the model, then waifu2x will crash with the following output:

> ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
DataPipeline/DPRunner.swift:90: Fatal error: buildPipeline() called in base class
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 6364790 kb/s
  Stream #0:0: Video: rawvideo (RGBA / 0x41424752), rgba, 3840x2160, 6364790 kb/s, 23.98 tbr, 23.98 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_videotoolbox))
Output #0, mp4, to 'output.mp4':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p, 3840x2160, q=2-31, 200 kb/s, 23.98 fps, 19184 tbn
    Metadata:
      encoder         : Lavc59.18.100 h264_videotoolbox
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
zsh: exit 1      ffmpeg -i input.mp4 -pix_fmt rgba -f rawvideo -loglevel quiet - | 
zsh: trace trap  waifu2x -m real_cugan --cugan-scale 2 --cugan-variant conservative --raw  192 | 
zsh: done        ffmpeg -f rawvideo -pix_fmt rgba -s:v 3840x2160 -r 23.98 -i - -c:v  output.mp

and the System will report that waifu2x quit unexpectedly. Other models work however. If I try to process the same video using your exemplary command

> alias waifu2x=/Applications/waifu2x.app/Contents/MacOS/waifu2x
ffmpeg -i input.mp4 -pix_fmt rgba -f rawvideo -loglevel quiet - |
  waifu2x -m real_esrgan -v anime_2x_video --raw --width 1920 --height 1080 |
  ffmpeg -f rawvideo -pix_fmt rgba -s:v 3840x2160 -r 23.98 -i - -c:v h264_videotoolbox output.mp4

then waifu2x and ffmpeg will process the video without issue using real-esrgan.

[waifu2x Crash Report.txt](https://github.com/imxieyi/waifu2x-ios/files/8543894/waifu2x.Crash.Report.txt)

**Comment by imxieyi** [comment]
This is definitely a bug. The next update will fix it.

**Comment by imxieyi** [comment]
The App Store review is surprisingly fast this time. Please update to the latest version (6.2.3) and it should be fixed.

**Comment by mmkzer0** [comment]
It is indeed fixed! Thank you very much for the quick reply.
