### ISSUE TITLE
Real-CUGAN模型缩放问题

### ISSUE THREAD

**Issue by MickMo** [imxieyi/waifu2x-ios#55]
Real-CUGAN 模型对观感提升明显，但是放大选项必选2X以上，我并不想更改分辨率，请问我要怎么操作呢？

**Comment by imxieyi** [comment]
可以考虑将输出图片导入photoshop、gimp等软件里面缩小。不过大部分缩小的方法可能导致画质不理想，请多试试不同的方案。

**Comment by imxieyi** [comment]
最新的版本（7.1）增加了“禁止放大”的选项，现在所有模型都可以选择不改变分辨率。
