### ISSUE TITLE
处理图片时报错

### ISSUE THREAD

**Issue by liudhzhyym** [imxieyi/waifu2x-ios#58]
使用Xcode14.0 + iPhone14 Pro Max真机测试，在处理图片时报错 [Unknown process name] CGImageCreate: invalid image byte order info for bitsPerPixel != 32 = 16384

看起来是创建结果图片时失败，请问这个问题需要怎么解决呢？

![waifu](https://user-images.githubusercontent.com/5382915/200276850-39fdab7e-ec8b-4bf2-9d16-088656790c48.jpg)

**Comment by imxieyi** [comment]
应该不是所有图片都有问题？这张是只有灰度的吗？如果不是的话能不能发一张有问题的图片？

**Comment by imxieyi** [comment]
最新的master版本应该已经解决，新版iOS看起来不允许创建只有3个channel的图片了。
