### ISSUE TITLE
Fake description on system requirement

### ISSUE THREAD

**Issue by iamPorter** [imxieyi/waifu2x-ios#60]
Now the App requires iOS 15 but you wrote that it only needs and was once successfully  tested on iOS 11. It must be a previous version’s test and it’s now not true.
I think you should change this.

**Comment by imxieyi** [comment]
The shared library [waifu2x](https://github.com/imxieyi/waifu2x-ios/tree/master/waifu2x) only requires iOS 11. The app in this repo is just a demo to show how the library works. You should embed the shared library into your own project which can target as low as iOS 11.

If you need a better UI please consider downloading the App Store version which includes all features in this repo for free.

The description can be changed to clarify this though.
