### ISSUE TITLE
Memory Is Full

### ISSUE THREAD

**Issue by Felix18928** [imxieyi/waifu2x-ios#61]
I exported one project and it worked fine. I am now trying to export my second project and it keeps saying memory is full. What do I do??? Please help

**Comment by imxieyi** [comment]
Are you trying to process videos on your iPhone? I will seriously consider removing video processing function from iOS version now since a lot of people expect their phone to performe as good as a RTX 4090.

**Comment by imxieyi** [comment]
If you enabled preprocessing feature while processing videos, it should be fixed in the latest version (6.2.6). Since there is no useful information provided here, I'm closing this issue. Feel free to reopen if you have more details to share.
