### ISSUE TITLE
内存不足什么时候解决

### ISSUE THREAD

**Issue by KoiYuri** [imxieyi/waifu2x-ios#62]
无语了啊 内存不足？没见过这样的 白买了 我ipad pro2021整视频整到一半说我内存不足？？？

**Comment by imxieyi** [comment]
你不会真的以为ipad pro上面有m1能跟mac一样（几乎）无限制使用内存？普通用户看来永远无法理解iOS平台开发有多坑。

这是我第n+10086次后悔给iOS版开放视频处理功能，在未来某个版本估计就没这功能了。要处理视频还是找个PC或者Mac吧。

**Comment by imxieyi** [comment]
另外，如果你不满意请考虑向Apple申请退款：https://support.apple.com/zh-cn/HT204084

**Comment by KoiYuri** [comment]
只能除理30秒之内的视频貌似

**Comment by KoiYuri** [comment]
越狱了能不能无限内存

**Comment by imxieyi** [comment]
重启也没用？你是用的什么模型？

**Comment by KoiYuri** [comment]
我就是重启后才整的 最后两个模型干到一半就提示内存不足

**Comment by KoiYuri** [comment]
又遇到一个问题 创建源缓冲区失败代码-21（显示的是英文）我的设备是ipad pro2021 15.1系统

**Comment by imxieyi** [comment]
如果你希望问题能解决，首先要冷静下来，然后提供有效而且具体的信息，例如：使用的模型、视频分辨率、视频格式、输出视频格式、放大倍数等。

**Comment by KoiYuri** [comment]
出现问题的都是后面两个模块

**Comment by KoiYuri** [comment]
视频分辨率分别是2k 跟4k 视频格式mp4 输出格式mp4 放大2倍

**Comment by KoiYuri** [comment]
就在刚刚出现了 无法调整图像大小-21771     2400x1350 mp4格式 大小2倍 输出2880x1620 Real-ESRGAN模型

**Comment by imxieyi** [comment]
你是不是还开了缩小功能？2400*2并不等于2880。

**Comment by KoiYuri** [comment]
是的我开了缩小

**Comment by KoiYuri** [comment]
出现了一个问题 未能完成操作（PhPhotosErrorDomain错误-1）

原视频3456x1944 mp4 
输出视频4008x2256 mp4
peal-cugan-动漫模型
放大2倍 缩小0.58倍数

**Comment by KoiYuri** [comment]
作者能不能添加一个放大选项 选择不放大呢 只调整降噪跟强度

**Comment by imxieyi** [comment]
缩小功能有内存泄漏问题，很快会有更新解决。

必须放大是因为模型限制，先放大后缩小效果可能不会很理想。

**Comment by KoiYuri** [comment]
我发现只要视频是3k-4k 不管是不是伪3-4k 貌似处理起来会出现内存问题 这是什么情况明明只有10m-20m左右

**Comment by imxieyi** [comment]
关掉缩小功能就好了。

**Comment by KoiYuri** [comment]
关掉它提示不支持 分辨率过高 我测试只能在4k内 可是视频伪4k

**Comment by imxieyi** [comment]
那就请稍微有点耐心，大概最近几天就会有更新解决这个问题。

**Comment by KoiYuri** [comment]
好的👌

**Comment by KoiYuri** [comment]
请问它这个内存不足是运行内存还是存储内存

**Comment by imxieyi** [comment]
运行内存。当然存储空间不够也是会失败的。

**Comment by KoiYuri** [comment]
无法持久密钥块什么情况😳

**Comment by imxieyi** [comment]
可以发个截图吗？

**Comment by KoiYuri** [comment]
![image](https://user-images.githubusercontent.com/52345579/206960294-85aa883e-e19f-48e1-be2e-bacf24656912.jpeg)
基本是这样 其它都用就是pan 插画不可以用

**Comment by imxieyi** [comment]
内存不足的问题刚发布的新版（6.2.6）已经解决了。pan不可用可能是暂时的问题，过一两天或许会自动恢复（之前出现过类似情况）。

**Comment by KoiYuri** [comment]
怎么新版本唰的一下更新好了？补丁？

**Comment by imxieyi** [comment]
mac app store有时候确实是incremental update，总之更新快肯定是好事。
