### ISSUE TITLE
在Mac上购买过额外模型，在ios上需要重复购买事正常的吗？

### ISSUE THREAD

**Issue by Shizuri23** [imxieyi/waifu2x-ios#63]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/46082179/206918101-90b933f6-e729-400f-acff-b2c79cc06980.png">

![image](https://user-images.githubusercontent.com/46082179/206918120-211ab449-527c-46f4-adb6-c9c71491b14a.png)

**Comment by imxieyi** [comment]
由于历史原因两个app以前是完全独立的，有很多用户已经购买过两个不同的版本，所以合并后继续保持内购分开。

未来有计划加入新的内购项目，将会支持iOS和macOS的通用购买。
