### ISSUE TITLE
iOS App 保存heic结果时无限转圈

### ISSUE THREAD

**Issue by SZCthebandit** [imxieyi/waifu2x-ios#65]
测试环境：iOS 15.3.1 - A10X iPad 10.5'' App Switcher内关闭其他所有程序
复现步骤：选择任意数量图片->选择任意可用的放大选项，但是把输出格式选为HEIC->计算完成->点击"Save/保存" ->app在某一张图片”保存中“无限转圈(30min+)并且无法继续使用，右下角”取消“并不会放弃这次保存，所有放大结果全部浪费。
绝大多数情况出现在第一张图片，剩下少数情况是最后一张，似乎与图片大小关系不大（已知任一边长>10000的heic在本机保存大概率都会出问题，但是测试图片输出均没有那么大）。
暂时解决方法：Airdrop到另一台15.4.1 A12 iPad mini放大后再Airdrop回该iPad，但是图片顺序信息完全丢失（图片序列1-2-3在该流程后保存回iPad就变成了3-1-2）

**Comment by imxieyi** [comment]
请问jpeg有同样的问题吗？

**Comment by SZCthebandit** [comment]
> 请问jpeg有同样的问题吗？

jpeg目前没有遇到过

**Comment by imxieyi** [comment]
才注意到这里指的是保存到相册中途卡死，抱歉。

这个问题大概率是iOS相册的bug，我记得在保存一些分辨率过高的图片时iOS相册会崩溃导致保存失败。所以可以尝试先导出到文件再尝试保存到相册。

最近的新版不再支持iOS 15，请问可以试一下iOS 16有同样的问题吗？

**Comment by SZCthebandit** [comment]
抱歉 很久没有关注issue; 我的设备为了越狱兼容性 暂不考虑升级至iOS16，不过您提到的_保存到文件_的方法确实降低了保存失败的几率，谢谢您的回应。
如果可以的话，我想问下新版不支持iOS15是什么原因？我无权评价开发，但是看到app这么快已经失去了iOS15兼容性，还是有些失望。

**Comment by imxieyi** [comment]
不再支持iOS 15是因为新的功能用到了一些iOS 16才增加的UI组件，而且几年前发生过因为测试不充分导致旧版iOS出现严重bug的情况。作为个人开发者要保证两个iOS大版本都不出问题的成本实在是过高，所以希望你可以理解。
