### ISSUE TITLE
[Feature Request] Add Remacri Upscaler

### ISSUE THREAD

**Issue by mattbisme** [imxieyi/waifu2x-ios#66]
I've been toying around with the [Draw Things](https://drawthings.ai) app for macOS/iOS and it includes various upscalers. One of the upscalers is one that I didn't recognize. I've found that Remacri performs rather well. More often than not, I prefer it over the others.

Although I'm speaking from my own experience, there are also [others that feel the same](https://www.reddit.com/r/StableDiffusion/comments/yr9xbk/extensive_research_of_upscalers_remacri_has_best/). Any chance we could get that as part of Waifu2x?

**Comment by imxieyi** [comment]
Looks like it's a ESRGAN model which is available on upscale.wiki: https://upscale.wiki/wiki/Model_Database

Currently there is a closed-beta version of waifu2x-ios which allows you to load custom models. Would you like to join the TestFlight beta and take an earlier look?

If so please send your Apple ID to support@waifu2x.app and I'll send you an invitation link.

**Comment by imxieyi** [comment]
The custom models feature has been released now. Remacri is included in the provided conversion script.
