### ISSUE TITLE
最近m2 芯片上直接卡死， 好奇怪

### ISSUE THREAD

**Issue by nevertoday** [imxieyi/waifu2x-ios#67]
![image](https://user-images.githubusercontent.com/166048/222890456-675e9d06-c7d6-4ea9-ada8-cd46c9f86554.png)

**Comment by imxieyi** [comment]
这是正常的，macOS因为app沙盒必须用绝对路径。把`aaa.jpg`改成`$(pwd)/aaa.jpg`就成绝对路径了，同理2.jpg也需要改

**Comment by nevertoday** [comment]
waifu2x  -m real_esrgan -i  /Users/admin/Downloads/aa.jpg -v photo_4x_sharp -o /Users/admin/Downloads/aa2.jpg 
我是这个也卡死了， 我替换多轮了，各种角度尝试了。 文件夹权限我也拖拽过来，给到过了， 感觉真的很奇怪~

**Comment by nevertoday** [comment]
我的方式是在macos 下面下载的软件， 不是通过brew 安装的， 当然我也尝试果brew 安装但是实际上还是不行
![image](https://user-images.githubusercontent.com/166048/222903488-fa7ef8bf-d595-40af-a806-29b11cb45e33.png)

**Comment by nevertoday** [comment]
![image](https://user-images.githubusercontent.com/166048/222903546-b6878d92-44f5-4dc0-81bc-23746739e8ac.png)

**Comment by imxieyi** [comment]
哦这个问题是macOS 13的bug，#57 也提到过。虽然没找到原因，但是后面更新添加的`--stub-ui`参数似乎能解决问题。可以尝试一下吗？

**Comment by nevertoday** [comment]
加了这个参数， 一切都好了， 而且速度超级快
waifu2x -m real_esrgan -i /Users/admin/Downloads/aa.jpg -v photo_4x_sharp --stub-ui -o /Users/admin/Downloads/aa2.jpg

**Comment by imxieyi** [comment]
还真有用，不知道Apple是怎么给弄坏的，听说waifu2x-ncnn-vulkan也有相同的问题。
