### ISSUE TITLE
CANNOT create file

### ISSUE THREAD

**Issue by XFLOWofficial** [imxieyi/waifu2x-ios#68]
Im trying to upscale a 2d video and there are many videos that have same issue: CANNOT CREATE FILE

**Comment by imxieyi** [comment]
Just a few things to clarify:
- Are you using iOS or macOS?
- Do you have problem processing images?
- Are you saving to a specified directory?

**Comment by XFLOWofficial** [comment]
Im using macOS. I upscale like 30 videos with no problem but 5 videos they appear the same error. Saving in the same file location. after the error I did upscale another videos with no problem

**Comment by XFLOWofficial** [comment]
I forget to mentions that I download the app from apple store on my Mac (just learning )

**Comment by imxieyi** [comment]
Did you try to process the same video file multiple times? The app will not try to overwrite existing files. Probably the error message can be improved though.

**Comment by XFLOWofficial** [comment]
I did that and it works. I changed the name to the files and where I was saving them on. Thank you

**Comment by imxieyi** [comment]
You should be using an old version of the app. I just realized that newer versions already overwrite existing files so that the behavior is consistent between images and videos.
