### ISSUE TITLE
大佬求教，waifu2x-caffe 的模型是怎么转换成CoreML的模型的？

### ISSUE THREAD

**Issue by Miku06** [imxieyi/waifu2x-ios#7]
在 waifu2x-caffe 项目中，只找到了.Json 后缀的Model。
https://github.com/lltcggie/waifu2x-caffe/tree/master/bin/models/anime_style_art

这个提供了caffemodel
 https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe/tree/master/Waifu2x-caffe/models/upconv_7_anime_style_art_rgb

用CoreML convert tool 具体转换的时候 还是会报错。
想知道 大佬 当时是怎么转换这个模型的。

**Comment by imxieyi** [comment]
建议参考readme，里面有转换方法
