### ISSUE TITLE
系统最低要求可以降低一点吗

### ISSUE THREAD

**Issue by Baryonds** [imxieyi/waifu2x-ios#70]
可以降低一下应用的要求系统吗 16.0太高了

**Comment by imxieyi** [comment]
技术上不可行，因为iOS 15支持一些Apple A9和A8设备，app现在利用了Apple A10开始才有的指令集优化zlib性能，在A9和A8设备上会造成启动app就崩溃。不过iOS 15虽然不能装最新版，app  store应该会提示安装支持的旧版。
