### ISSUE TITLE
Xcode Project is different from the lastest version in App Store

### ISSUE THREAD

**Issue by DermXZ** [imxieyi/waifu2x-ios#73]
![image](https://github.com/imxieyi/waifu2x-ios/assets/82532035/3886def7-cee1-49f0-9a7c-c0816072d026)
I'm using Xcode 12.4 and MacOS Catalina 10.15

The app store version:
![image](https://github.com/imxieyi/waifu2x-ios/assets/82532035/bfc40ee8-c9bc-4df0-88da-97da61340b22)

Thanks!

**Comment by imxieyi** [comment]
This repo is only meant to be used as library of your own apps. The interface here is only a demo showing how to use the library. If you are not building your own apps you can just use the app store version.

**Comment by DermXZ** [comment]
I loved the interface and I wanted to make something similar, also use the different options of upscaling but I don't know anything about Xcode, I wanted to see the code and understand how did you make it

**Comment by imxieyi** [comment]
The unfortunate reality is that whenever you open source an iOS/macOS app, regardless of license, someone will take the code and release it almost as-is on the App Store and charge money. This once happened to me and I had no choice but to fork the GUI code to a private repo.

The App Store version is built with SwiftUI. I recommend you get started with the official document: https://developer.apple.com/xcode/swiftui/

**Comment by DermXZ** [comment]
Ok I will start with that, thank you!
