### ISSUE TITLE
"Cannot Open"

### ISSUE THREAD

**Issue by troopaofficial** [imxieyi/waifu2x-ios#74]
Cannot open any MKV file from personal rips. Only thing it says is "cannot open" | running m2 chip on Mac mini.

**Comment by troopaofficial** [comment]
Same thing on m1 MacBook Pro. both computers updated to Sonoma 14.5

**Comment by imxieyi** [comment]
This app depends on macOS's built-in video support. If you cannot open the file with QuickTime Player, the app will not be able to open it. Please convert it to a supported format (e.g. MP4).

**Comment by troopaofficial** [comment]
Converting to MP4 works thank you.
