### ISSUE TITLE
cannot 

### ISSUE THREAD

**Issue by the-biggest-birfd** [imxieyi/waifu2x-ios#76]
cannot select downloads as output path

or any other place for that matter

i press open and nothing happens

**Comment by imxieyi** [comment]
Could you provide more details for your issue?

1. The device you are using.
2. The iOS or macOS version.
3. The app version.
4. A screen recording demonstrating the issue is the best.

**Comment by the-biggest-birfd** [comment]
![CleanShot 2024-09-06 at 08 26 19@2x](https://github.com/user-attachments/assets/498130cd-f8e8-4d2b-9b3c-d20aef4b3df4)
v7.2.7 (23694)

while recording i realized that it fixed itself so I'm gonna close the issue
