### ISSUE TITLE
iOS18 does not work.

### ISSUE THREAD

**Issue by nabettu** [imxieyi/waifu2x-ios#77]
I have not been able to determine whether the issue lies with the model or the application, but when trying to increase the resolution on iOS18, the image just ends up being stretched out without any improvement in quality.

**Comment by imxieyi** [comment]
Could you provide more details?

- The model you are using.
- The app version.
- An example pair of input and output images is the best.

**Comment by nabettu** [comment]
I'm sorry, it was a misunderstanding.
