### ISSUE TITLE
[Bug] Crash when importing or using partially customized models.

### ISSUE THREAD

**Issue by Miracle-Sakuno** [imxieyi/waifu2x-ios#84]
Waifu2x-iOS for macOS

App Version: 7.2.9 (23737)

OS Version: macOS Sequoia 15.1 (24B5070a)

[Model source](https://github.com/imxieyi/waifu2x-ios-model-converter)

Program crashes when importing or using partially customized models.Trying to convert the model yourself via a converter or using a pre-converted model did not solve the problem.

Compatibility normal list: 
![working normally](https://github.com/user-attachments/assets/f747acb1-7d0b-4a99-9663-344fa4ec801b)

Compatibility exception list:
![Compatibility exception](https://github.com/user-attachments/assets/2b32250f-baf1-4d3d-8ed2-2b0d8d661a32)

[waifu2x Crash.txt](https://github.com/user-attachments/files/17321435/waifu2x.Crash.txt)

**Comment by Miracle-Sakuno** [comment]
I tried completely uninstalling and reinstalling waifu2x-iOS for Mac, but the problem still recurred.

**Comment by imxieyi** [comment]
It's the same problem as Real-CUGAN crash:

```
/AppleInternal/Library/BuildRoots/e0873e53-5185-11ef-9a51-9ab6d782fe32/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphExecutable.mm:122: failed assertion `Error: unhandled platform for MPSGraph serialization'
```

Looks like it's a problem only with [Mac Catalyst](https://developer.apple.com/mac-catalyst/) apps. The same models load without issue in Mac apps.

**Comment by Miracle-Sakuno** [comment]
What do I need to do to repair it?

Do you have a plan to reconstruct the App with the SwiftUI?

**Comment by imxieyi** [comment]
The latest version (7.2.10) implemented a workaround for this issue. Feel free to update.

**Comment by Miracle-Sakuno** [comment]
The problem has been solved, thanks for your work.
