### ISSUE TITLE
Add this screenshot to readme?

### ISSUE THREAD

**Issue by Co2333** [imxieyi/waifu2x-ios#9]
It is fucking faster then my GTX 1080 I can't believe it!
![tim 20181018000510](https://user-images.githubusercontent.com/25259084/47100202-90f25600-d269-11e8-8cbe-1e462205b4b7.png)

**Comment by imxieyi** [comment]
It's not possible. There must be something wrong with the setup on your pc, e.g. waifu2x is running on the CPU instead of GPU.
